// Module 3 — Inventory & Listings (ARCH §3). Owns app.inventory_item and app.listing and the
// listing lifecycle (STATE_MACHINES §1). It orchestrates content approval and policy versions
// through the Listing Content and Seller Policy modules' interfaces; it never calls a model.
export { LISTING_STATUSES, LISTING_TRANSITIONS, isListingTransitionAllowed } from './lifecycle.ts';
export {
  CreateListingWithItemInputSchema,
  LIST_QUERY_TIMEOUT_MS,
  LISTING_PAGE_DEFAULT,
  LISTING_PAGE_MAX,
  ListingPositionSchema,
  ReplaceFactsInputSchema,
  SaveSellerDraftInputSchema,
  SetPolicyInputSchema,
  approveContent,
  archiveListing,
  cancelListing,
  createInventoryItem,
  createListing,
  createListingWithItem,
  expireListing,
  getContentHistory,
  getCurrentPolicy,
  getListing,
  getListingWorkspace,
  listListings,
  markListed,
  markReady,
  relistListing,
  readinessGaps,
  replaceFacts,
  revertToDraft,
  saveSellerDraft,
  setAskingPrice,
  setPolicy,
  type CloseListingResult,
  type ContentHistory,
  type ContentHistoryInput,
  type CurrentPolicy,
  type CreateListingWithItemInput,
  type InventoryItemRecord,
  type ListingPage,
  type ListingPosition,
  type ListingRecord,
  type ListingWorkspace,
  type ListListingsInput,
  type MarkListedResult,
  type SaveSellerDraftInput,
  type SetPolicyInput,
  type SetPolicyResult,
  type SellerDraftResult,
} from './service.ts';
