// Module 3 — Inventory & Listings (ARCH §3). Owns app.inventory_item and app.listing and the
// listing lifecycle (STATE_MACHINES §1). It orchestrates content approval and policy versions
// through the Listing Content and Seller Policy modules' interfaces; it never calls a model.
export { LISTING_STATUSES, LISTING_TRANSITIONS, isListingTransitionAllowed } from './lifecycle.ts';
export {
  CreateListingWithItemInputSchema,
  ReplaceFactsInputSchema,
  SaveSellerDraftInputSchema,
  approveContent,
  archiveListing,
  cancelListing,
  createInventoryItem,
  createListing,
  createListingWithItem,
  expireListing,
  getListing,
  getListingWorkspace,
  markListed,
  markReady,
  relistListing,
  readinessGaps,
  replaceFacts,
  revertToDraft,
  saveSellerDraft,
  setAskingPrice,
  setPolicy,
  type CloseListingResult,
  type CreateListingWithItemInput,
  type InventoryItemRecord,
  type ListingRecord,
  type ListingWorkspace,
  type MarkListedResult,
  type SaveSellerDraftInput,
  type SellerDraftResult,
} from './service.ts';
