-- 0004_public_access.sql
--
-- Forward-only (OPS-513, OPS-514). Applied once by app_migrator after 0003.
--
-- Slice 1b: the public-access domain foundation of architecture/DOMAIN_MODEL.md
-- (PublicListingAccess, ListingAccessCode; DM-08, DM-09), architecture/STATE_MACHINES.md §1
-- (SM-L-02) and §2 (SM-C-01 to SM-C-03), security/PUBLIC_ACCESS_SECURITY.md and D-02, D-03.
-- No buyer route exists (D-18): nothing here is reachable except through the tenant-scoped
-- domain services, under row-level security like every other seller-owned table.
--
-- The code is public by design (D-03) and is still never persisted in plaintext (DM-08, OPS-710,
-- ACCESS-013, DATA-106): the only stored form is a salted scrypt hash in a self-describing string,
-- and a CHECK refuses any value without that shape, so a six-digit value cannot be written.
-- No error raised here interpolates a code (SEC-040, OPS-566).

CREATE TYPE app.access_code_status AS ENUM ('ACTIVE', 'ROTATED', 'REVOKED', 'EXPIRED');

-- PublicListingAccess: the buyer-facing surface for one listing. The opaque public id is the
-- unguessable component of the buyer URL (SEC-003, OPS-711, BUYER-002): sixteen lowercase base32
-- characters carrying 80 CSPRNG bits, generated by the application and derived from nothing.
-- `enabled` opens and closes the surface without touching the listing (ARCH module 6).
CREATE TABLE app.public_listing_access (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  seller_id    uuid        NOT NULL REFERENCES app.seller (id),
  listing_id   uuid        NOT NULL,
  public_id    text        NOT NULL CHECK (public_id ~ '^[a-z2-7]{16}$'),
  enabled      boolean     NOT NULL DEFAULT true,
  -- OPS-738: mutable rows carry a version and are updated with an optimistic predicate.
  row_version  integer     NOT NULL DEFAULT 1 CHECK (row_version >= 1),
  -- OPS-720: the request that last wrote this row.
  request_id   text        NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT public_listing_access_listing_same_tenant FOREIGN KEY (listing_id, seller_id)
    REFERENCES app.listing (id, seller_id),
  -- DM-09: one public access per listing. Rotation and re-issue keep the URL (BUYER-003).
  CONSTRAINT public_listing_access_one_per_listing UNIQUE (listing_id),
  CONSTRAINT public_listing_access_public_id_unique UNIQUE (public_id),
  CONSTRAINT public_listing_access_id_seller UNIQUE (id, seller_id)
);
ALTER TABLE app.public_listing_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.public_listing_access FORCE ROW LEVEL SECURITY;
CREATE POLICY public_listing_access_tenant_isolation ON app.public_listing_access
  USING (seller_id = app.current_seller_id())
  WITH CHECK (seller_id = app.current_seller_id());

-- ListingAccessCode: one row per issued code, bound to one public access (DM-08, DM-09), with a
-- version number so rotation is traceable. Per-client failed-attempt counters and lockout state
-- (SM-C-04) belong to the buyer gate and are not part of this slice.
CREATE TABLE app.listing_access_code (
  id                 uuid                   PRIMARY KEY DEFAULT gen_random_uuid(),
  seller_id          uuid                   NOT NULL REFERENCES app.seller (id),
  public_access_id   uuid                   NOT NULL,
  version_number     integer                NOT NULL CHECK (version_number >= 1),
  status             app.access_code_status NOT NULL DEFAULT 'ACTIVE',
  -- OPS-710: "$scrypt$ln=<log2 N>,r=<r>,p=<p>$<salt base64>$<key base64>". Never the code.
  code_hash          text                   NOT NULL CHECK (
    code_hash ~ '^\$scrypt\$ln=[0-9]{1,2},r=[0-9]{1,3},p=[0-9]{1,3}\$[A-Za-z0-9+/]{16,}={0,2}\$[A-Za-z0-9+/]{32,}={0,2}$'
  ),
  issued_at          timestamptz            NOT NULL DEFAULT now(),
  -- ACCESS-012: expiry is off by default. Nothing in this slice sets it.
  expires_at         timestamptz,
  status_changed_at  timestamptz            NOT NULL DEFAULT now(),
  request_id         text                   NOT NULL,
  CONSTRAINT listing_access_code_access_same_tenant FOREIGN KEY (public_access_id, seller_id)
    REFERENCES app.public_listing_access (id, seller_id),
  CONSTRAINT listing_access_code_version_unique UNIQUE (public_access_id, version_number),
  CONSTRAINT listing_access_code_expiry_after_issue CHECK (expires_at IS NULL OR expires_at > issued_at)
);
-- SM-C-01, DM-09, OPS-737: at most one ACTIVE code per public access at any instant.
CREATE UNIQUE INDEX listing_access_code_one_active ON app.listing_access_code (public_access_id)
  WHERE status = 'ACTIVE';
CREATE INDEX listing_access_code_by_access ON app.listing_access_code (seller_id, public_access_id, version_number);
ALTER TABLE app.listing_access_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.listing_access_code FORCE ROW LEVEL SECURITY;
CREATE POLICY listing_access_code_tenant_isolation ON app.listing_access_code
  USING (seller_id = app.current_seller_id())
  WITH CHECK (seller_id = app.current_seller_id());

-- ---------------------------------------------------------------------------------------------
-- Guards (OPS-705 to OPS-707, OPS-738): the data layer rejects what the state machines do not draw
-- ---------------------------------------------------------------------------------------------

CREATE FUNCTION app.public_listing_access_guard() RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'a public access record is never deleted; the surface is disabled instead'
      USING ERRCODE = 'PA001';
  END IF;
  IF NEW.id <> OLD.id OR NEW.seller_id <> OLD.seller_id OR NEW.listing_id <> OLD.listing_id
     OR NEW.public_id <> OLD.public_id OR NEW.created_at <> OLD.created_at THEN
    RAISE EXCEPTION 'public access identity columns are immutable (BUYER-003)' USING ERRCODE = 'PA001';
  END IF;
  IF NEW.row_version <> OLD.row_version + 1 THEN
    RAISE EXCEPTION 'a public access update increments row_version by exactly one (OPS-738)'
      USING ERRCODE = 'PA002';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END
$fn$;
CREATE TRIGGER public_listing_access_guard BEFORE UPDATE OR DELETE ON app.public_listing_access
  FOR EACH ROW EXECUTE FUNCTION app.public_listing_access_guard();

-- STATE_MACHINES §2, exactly the drawn edges: a code leaves ACTIVE once and never returns.
CREATE FUNCTION app.access_code_transition_allowed(old_status app.access_code_status, new_status app.access_code_status)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $fn$
  SELECT old_status = 'ACTIVE' AND new_status IN ('ROTATED', 'REVOKED', 'EXPIRED')
$fn$;

CREATE FUNCTION app.access_code_guard() RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    -- DATA_AND_PRIVACY §3: the hash outlives the code for abuse forensics; nothing deletes it here.
    RAISE EXCEPTION 'an access code is never deleted' USING ERRCODE = 'AC002';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'ACTIVE' THEN
      RAISE EXCEPTION 'an access code is issued ACTIVE (STATE_MACHINES §2)' USING ERRCODE = 'AC001';
    END IF;
    RETURN NEW;
  END IF;
  IF NEW.id <> OLD.id OR NEW.seller_id <> OLD.seller_id OR NEW.public_access_id <> OLD.public_access_id
     OR NEW.version_number <> OLD.version_number OR NEW.code_hash <> OLD.code_hash
     OR NEW.issued_at <> OLD.issued_at OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
    RAISE EXCEPTION 'access code identity, hash, version and expiry are immutable' USING ERRCODE = 'AC002';
  END IF;
  IF NEW.status <> OLD.status THEN
    IF NOT app.access_code_transition_allowed(OLD.status, NEW.status) THEN
      RAISE EXCEPTION 'illegal access code transition % -> % (STATE_MACHINES §2)', OLD.status, NEW.status
        USING ERRCODE = 'AC001';
    END IF;
    NEW.status_changed_at := now();
  ELSIF NEW.status_changed_at <> OLD.status_changed_at THEN
    RAISE EXCEPTION 'status_changed_at follows the status and is not set directly' USING ERRCODE = 'AC002';
  END IF;
  RETURN NEW;
END
$fn$;
CREATE TRIGGER access_code_guard BEFORE INSERT OR UPDATE OR DELETE ON app.listing_access_code
  FOR EACH ROW EXECUTE FUNCTION app.access_code_guard();

-- SM-L-02 at the data layer: a listing does not become LISTED without an enabled public access
-- carrying one ACTIVE, unexpired code. Runs after app.listing_guard (trigger names fire in
-- alphabetical order), so an undrawn transition is still reported as LS001 first.
CREATE FUNCTION app.listing_listed_guard() RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.status = 'LISTED' AND OLD.status <> 'LISTED' THEN
    IF NOT EXISTS (
      SELECT 1
        FROM app.public_listing_access a
        JOIN app.listing_access_code c
          ON c.public_access_id = a.id AND c.seller_id = a.seller_id
       WHERE a.listing_id = NEW.id AND a.seller_id = NEW.seller_id AND a.enabled
         AND c.status = 'ACTIVE' AND (c.expires_at IS NULL OR c.expires_at > now())
    ) THEN
      RAISE EXCEPTION 'listing cannot become LISTED without an enabled public access and an ACTIVE code (SM-L-02)'
        USING ERRCODE = 'LS005';
    END IF;
  END IF;
  RETURN NEW;
END
$fn$;
CREATE TRIGGER listing_listed_guard BEFORE UPDATE ON app.listing
  FOR EACH ROW EXECUTE FUNCTION app.listing_listed_guard();

-- ---------------------------------------------------------------------------------------------
-- Runtime grants: DML only. Status and surface state change; nothing is deleted.
-- ---------------------------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE ON app.public_listing_access TO app_runtime;
GRANT SELECT, INSERT, UPDATE ON app.listing_access_code TO app_runtime;
